# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  frontend:
    docker:
      # specify the version you desire here
    - image: vuejs/ci

    working_directory: ~/circle-ci-test2/client

    steps:
    - checkout:
        path: ~/circle-ci-test2

      # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run:
        name: install npm 
        command: npm install

    - save_cache:
        paths:
          - node_modules
          - package.json
        key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
    - run: 
        name: Run Frontend Tests
        command: npm run test:unit
    - store_artifacts:
          path: test-results/vue
          destination: vue

    - store_test_results:
        path: test-results/vue    

  backend:
    docker:

    - image: circleci/python:3.8
    working_directory: ~/circle-ci-test2/server
    steps:
      - checkout:
          path: ~/circle-ci-test2

      # Cache dependencies
      - restore_cache:
          keys:
          - nerv-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found                
          - nerv-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: nerv-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run Backend Tests
          command: |
            . venv/bin/activate
            python -m pytest --html=test-results/pytest/nerveblox_test_results.html
      - store_artifacts:
          path: test-results/pytest
          destination: pytest

      - store_test_results:
          path: test-results/pytest   
workflows:
  version: 2
  nerveblox-test:
    jobs:
      - frontend
      - backend