# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  frontend:
    docker:
      # specify the version you desire here
    - image: vuejs/ci

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/circle-ci-test2/client

    steps:
    - checkout:
        path: ~/circle-ci-test2

      # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
          - package.json
        key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
    - run: npm run test:unit 
workflows:
  version: 2
  nerveblox-test:
    jobs:
      - frontend
          